### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Hasumi-Uehara** [Hasumi-Uehara/furima-32482#9]
# フリマアプリの動作確認をお願いします
お疲れ様です。
アプリケーションのデプロイおよびBasic認証設定をしましたので、
改めて動作確認をお願いいたします＾＾

## URL
https://furima-32482.herokuapp.com/
## Basic認証のIDとパスワード
ID：hasmin
パスワード：2222
## 出品者用のメールアドレスとパスワード
ユーザー名：はすぴょこ
メールアドレス：has@has
パスワード：hashas55
## 購入者用のメールアドレスとパスワード
ユーザー名：山太郎
メールアドレス：yamada@tarou
パスワード：yamada55
## 購入用の番号・期限・セキュリティコード
番号（16桁）：4242424242424242
期限（月/年）：3/24
セキュリティコード：123

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]

- [x] ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品購入ページへ遷移しようとすると、
トップページに遷移するようにしましょう

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Hasumi-Uehara** [comment]
# フリマアプリの動作確認をお願いします（2回目）
お疲れ様です。
上記の不備を修正しました！ご指摘ありがとうございます。
改めて動作確認をお願いいたします＾＾

## URL
https://furima-32482.herokuapp.com/
## Basic認証のIDとパスワード
ID：hasmin
パスワード：2222
## 出品者用のメールアドレスとパスワード
ユーザー名：はすぴょこ
メールアドレス：has@has
パスワード：hashas55
## 購入者用のメールアドレスとパスワード
ユーザー名：山太郎
メールアドレス：yamada@tarou
パスワード：yamada55
## 購入用の番号・期限・セキュリティコード
番号（16桁）：4242424242424242
期限（月/年）：3/24
セキュリティコード：123

**Comment by naru6117** [comment]
ご提出ありがとうございます‼︎
また、issueの内容も丁寧にご記載いただき、ありがとうございます✨
問題なく正常に動作することが確認できました！　
**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/49669977/103146935-74300200-4793-11eb-8c8c-8bb02d7edda8.png)

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**

**Comment by Hasumi-Uehara** [comment]
いやっほーーーーーーーーーーい＼(^ω^)／💖
LGTMうれしい泣ける最高〜〜〜〜〜！！！！！！

学習を始めてから約2ヶ月、ここにたどり着くまでの道のりもすごく濃かったけど、
エンジニアとしてのスタートラインにも立っていないなんて＞＜
すごい世界ですね（笑）

ただ、多くの方が学習を挫折してしまう内容を、
この短期間で習得できたことに心から感謝いたします＾＾

追加実装、オリジナルアプリ制作、その他の言語学習など、
今の自分に甘んじず、引き続きがんばります＼(^ω^)／
ありがとうございます😆✨
